dist: bionic
addons:
  apt:
    packages:
      - cmake
      - valgrind
matrix:
  fast_finish: true
  include:
    - language: rust
      os: linux
      rust: stable
    - language: rust
      os: osx
      osx_image: xcode10.1
      rust: stable

script: ci/script.sh